export const SET_WALLET = 'SET_WALLET'
export const GET_WALLET = 'GET WALLET'

export const SET_NETWORK = 'SET_NETWORK'
export const SET_MY_GAMES = 'SET_MY_GAMES'

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const GET_AUTHENTICATED = 'GET_AUTHENTICATED'

export const SET_INITIALIZED = 'SET_INITIALIZED'

export const SET_FOOTBALL_OPEN_GAMES = 'SET_FOOTBALL_OPEN_GAMES'
export const SET_CRICKET_OPEN_GAMES = 'SET_CRICKET_OPEN_GAMES'
export const SET_BASKETBALL_OPEN_GAMES = 'SET_BASKETBALL_OPEN_GAMES'
export const SET_MARKET_OPEN_GAMES = 'SET_MARKET_OPEN_GAMES'

export const SET_FOOTBALL_HOSTED_GAMES = 'SET_FOOTBALL_HOSTED_GAMES'
export const SET_CRICKET_HOSTED_GAMES = 'SET_CRICKET_HOSTED_GAMES'
export const SET_BASKETBALL_HOSTED_GAMES = 'SET_BASKETBALL_HOSTED_GAMES'
export const SET_MARKET_HOSTED_GAMES = 'SET_MARKET_HOSTED_GAMES'
export const SET_CHESS_HOSTED_GAMES = 'SET_CHESS_HOSTED_GAMES'

export const SET_FOOTBALL_LIVE_GAMES = 'SET_FOOTBALL_LIVE_GAMES'
export const SET_CRICKET_LIVE_GAMES = 'SET_CRICKET_LIVE_GAMES'
export const SET_BASKETBALL_LIVE_GAMES = 'SET_BASKETBALL_LIVE_GAMES'
export const SET_MARKET_LIVE_GAMES = 'SET_MARKET_LIVE_GAMES'

export const SET_FOOTBALL_COMPLETED_GAMES = 'SET_FOOTBALL_COMPLETED_GAMES'
export const SET_CRICKET_COMPLETED_GAMES = 'SET_CRICKET_COMPLETED_GAMES'
export const SET_BASKETBALL_COMPLETED_GAMES = 'SET_BASKETBALL_COMPLETED_GAMES'
export const SET_MARKET_COMPLETED_GAMES = 'SET_MARKET_COMPLETED_GAMES'

export const SET_REFETCH_CRICKET_GAMES = 'SET_REFETCH_CRICKET_GAMES'
export const SET_REFETCH_FOOTBALL_GAMES = 'SET_REFETCH_FOOTBALL_GAMES'
export const SET_REFETCH_BASKETBALL_GAMES = 'SET_REFETCH_BASKETBALL_GAMES'
export const SET_REFETCH_MARKET_GAMES = 'SET_REFETCH_MARKET_GAMES'

export const SET_RESET_REFETCH_FOOTBALL_GAMES =
  'SET_RESET_REFETCH_FOOTBALL_GAMES'
export const SET_RESET_REFETCH_CRICKET_GAMES = 'SET_RESET_REFETCH_CRICKET_GAMES'
export const SET_RESET_REFETCH_BASKETBALL_GAMES =
  'SET_RESET_REFETCH_BASKETBALL_GAMES'
export const SET_RESET_REFETCH_CHESS_GAMES = 'SET_RESET_REFETCH_CHESS_GAMES'
export const SET_RESET_REFETCH_MARKET_GAMES = 'SET_RESET_REFETCH_MARKET_GAMES'

export const SET_STATS = 'SET_STATS'
export const SET_LEADERBOARD = 'SET_LEADERBOARD'

export const SET_SINGLE_GAMES = 'SET_SINGLE_GAMES'
export const RESET_SINGLE_GAMES = 'RESET_SINGLE_GAMES'
export const SET_THEME = 'SET_THEME'
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET'

export const SET_CHESS_PLAYER = 'SET_CHESS_PLAYER'
export const SET_CHESS_LIVE_GAMES = 'SET_CHESS_LIVE_GAMES'
export const SET_CHESS_PLAYER_GAMES = 'SET_CHESS_PLAYER_GAMES'
export const SET_CHESS_COMPLETED_GAMES = 'SET_CHESS_COMPLETED_GAMES'
export const SET_CHESS_GAME_NAMES = 'SET_CHESS_GAME_NAMES'

export const SET_LUDO_DEBUGGER = 'SET_LUDO_DEBUGGER'
export const SET_LUDO_PLAYER = 'SET_LUDO_PLAYER'
export const SET_LUDO_HOSTED_GAMES = 'SET_LUDO_HOSTED_GAMES'
export const SET_LUDO_LIVE_GAMES = 'SET_LUDO_LIVE_GAMES'
export const SET_LUDO_COMPLETED_GAMES = 'SET_LUDO_COMPLETED_GAMES'
